var resp = {
    "message":"成功",
    "status":200,
    "data":{
        "regulatoryObjectCount":23213,
        "zfUserCount":[
            {"yearPeriod":"2015","count":25},
            {"yearPeriod":"2016","count":13},
            {"yearPeriod":"2017","count":10},
            {"yearPeriod":"2018","count":0},
            {"yearPeriod":"2019","count":19}
        ],
        "zfUserAllCount":1329,
        "checkActionCount":[
            {"yearPeriod":"2015","count":8},
            {"yearPeriod":"2016","count":18},
            {"yearPeriod":"2017","count":26},
            {"yearPeriod":"2018","count":10},
            {"yearPeriod":"2019","count":2}
        ],
        "checkActionAllCount":120,
        "punishCount":[
            {"yearPeriod":"2015","count":30},
            {"yearPeriod":"2016","count":25},
            {"yearPeriod":"2017","count":10},
            {"yearPeriod":"2018","count":5},
            {"yearPeriod":"2019","count":39}
        ],
        "punishAllCount":40,
        "reportCount":57,
        "amountOfFine":[
            {"yearPeriod":"2015","count":22000},
            {"yearPeriod":"2016","count":415616},
            {"yearPeriod":"2017","count":172515},
            {"yearPeriod":"2018","count":505236},
            {"yearPeriod":"2019","count":100052}
        ],
        "lawsRegulatCount":111,
        "checkResult":[
            {"yearPeriod":"未发现问题终止检查并向监管对象告知检查结果","count":4},
            {"yearPeriod":"发现问题做出责令改正等行政命令","count":4},
            {"yearPeriod":"发现问题做出行政指导","count":2}
        ],
        "punishKinds":[
            {"yearPeriod":"警告","count":16},
            {"yearPeriod":"罚款","count":5},
            {"yearPeriod":"责令停产停业","count":2},
            {"yearPeriod":"法律、行政法规规定的其他行政处罚","count":3}
        ],
        "checkMothod":[
            {"yearPeriod":"“双随机、一公开”监管","count":7},
            {"yearPeriod":"重点监管","count":3}
        ],
        "objectCheckCount":[
            {"yearPeriod":"中国光大银行股份有限公司","count":100001},
            {"yearPeriod":"中国银行股份有限公司温州市分行","count":2},
            {"yearPeriod":"渤海银行股份有限公司","count":30},
            
            {"yearPeriod":"绍兴银行股份有限公司嘉兴分行","count":1},
            {"yearPeriod":"泰康人寿保险股份有限公司鄂州中心支公司泽林营销服务部","count":1},
            {"yearPeriod":"中国人民财产保险股份有限公司顺昌支公司","count":1},
            {"yearPeriod":"中国人民财产保险股分有限公司襄城支公司山头店乡营销服务部","count":1},
        ],
        "penaltyOfCount":[
            {"yearPeriod":"摩根士丹利国际银行（中国）有限公司","count":8},
            {"yearPeriod":"华贵人寿","count":3},
            {"yearPeriod":"中国邮政储蓄银行股份有限公司","count":3},
            {"yearPeriod":"永诚财险","count":2},
            {"yearPeriod":"平安银行","count":1},
            {"yearPeriod":"厦门国际银行股份有限公司","count":1},
            {"yearPeriod":"华商银行","count":1},
            {"yearPeriod":"浙商银行股份有限公司","count":1},
            {"yearPeriod":"招商银行股份有限公司","count":1}],
            "amountOfPenalty":[
                {"yearPeriod":"泰康人寿保险股份有限公司鄂州中心支公司东沟营销服务部","count":4},
                {"yearPeriod":"中国农业银行股份有限公司","count":1000},
                {"yearPeriod":"上海浦东发展银行股份有限公司","count":333},
                
                {"yearPeriod":"中国建设银行股份有限公司","count":13},
                {"yearPeriod":"华夏银行股份有限公司","count":12},
                {"yearPeriod":"交通银行股份有限公司","count":11},
                {"yearPeriod":"中国民生银行股份有限公司","count":11},
                {"yearPeriod":"新联商业银行","count":10}
            ],
            "accusCount":12,
            "complaintCount":45
        },
        "detailMsg":null
    }